alias cls='clear'
alias py='python3'
alias ram='neofetch -d "memory"'
alias locip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"


PS1='\[\033[01;32m\] ╭─\u\[\033[00m\] at \[\033[01;35m\]\h ($(locip))\[\033[00m\] in \[\033[01;34m\]\w\n \[\033[01;32m\]╰─$ \[\033[00m\]'
export PS1
